"""
weekly_report.py - Weekly Report Generator for Dar Drip OS

How to use:
  1. Make sure you have logged content in data/raw/content.csv
  2. Make sure you ran the pipelines first
  3. Run: python scripts/weekly_report.py
  4. Your report appears in /reports/week_YYYY-MM-DD.md

The report is written for a founder, not a data scientist.
Plain language. Actionable. Fast to read.
"""

import sys
import pandas as pd
from datetime import datetime, date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from config import (
    CONTENT_FILE, TRENDS_FILE, PRODUCTS_FILE,
    REPORTS_DIR, WINNER_LABELS, WEAK_LABELS, BRAND_NAME
)


def load_data():
    """Load the raw data files. Runs pipelines first if needed."""
    data = {}

    if CONTENT_FILE.exists():
        data["content"] = pd.read_csv(CONTENT_FILE)
    else:
        data["content"] = pd.DataFrame()

    if TRENDS_FILE.exists():
        data["trends"] = pd.read_csv(TRENDS_FILE)
    else:
        data["trends"] = pd.DataFrame()

    if PRODUCTS_FILE.exists():
        data["products"] = pd.read_csv(PRODUCTS_FILE)
    else:
        data["products"] = pd.DataFrame()

    return data


def analyze_content(df):
    """Extract key content insights."""
    if df.empty:
        return {}

    result = {}

    # Normalize verdict
    df = df.copy()
    df["verdict"] = df["verdict"].fillna("").str.lower()
    df["views_24h"] = pd.to_numeric(df["views_24h"], errors="coerce").fillna(0)
    df["saves"] = pd.to_numeric(df["saves"], errors="coerce").fillna(0)
    df["shares"] = pd.to_numeric(df["shares"], errors="coerce").fillna(0)
    df["orders"] = pd.to_numeric(df["orders"], errors="coerce").fillna(0)

    # Best hook (by views)
    if "hook" in df.columns and not df.empty:
        best_row = df.loc[df["views_24h"].idxmax()]
        result["best_hook"] = str(best_row.get("hook", "N/A"))
        result["best_hook_views"] = int(best_row.get("views_24h", 0))
        result["best_hook_format"] = str(best_row.get("format", "N/A"))

    # Best format by average views
    if "format" in df.columns:
        format_avg = df.groupby("format")["views_24h"].mean()
        if not format_avg.empty:
            result["best_format"] = format_avg.idxmax()
            result["best_format_avg_views"] = int(format_avg.max())

    # Top trend source
    if "trend_source" in df.columns:
        source_counts = df["trend_source"].value_counts()
        if not source_counts.empty:
            result["top_trend_source"] = source_counts.index[0]

    # Winners
    winners = df[df["verdict"].isin(WINNER_LABELS)]
    result["winners"] = winners[["hook", "format", "views_24h", "orders"]].to_dict("records")

    # Weak content
    weak = df[df["verdict"].isin(WEAK_LABELS)]
    result["weak"] = weak[["hook", "format", "notes"]].to_dict("records")

    # Total orders this week
    result["total_orders"] = int(df["orders"].sum())

    return result


def analyze_trends(df):
    """Extract top trends."""
    if df.empty:
        return {}

    df = df.copy()
    for col in ["dar_drip_fit_score", "content_potential_score"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0)

    result = {}
    if "dar_drip_fit_score" in df.columns and "trend_name" in df.columns:
        top = df.nlargest(3, "dar_drip_fit_score")
        result["top_trends"] = top[["trend_name", "category", "dar_drip_fit_score"]].to_dict("records")

    return result


def analyze_products(df):
    """Extract top product idea."""
    if df.empty:
        return {}

    df = df.copy()
    df["orders"] = pd.to_numeric(df.get("orders", 0), errors="coerce").fillna(0)

    interest_map = {"high": 3, "medium": 2, "low": 1}
    df["_sort"] = df.get("interest_level", "").str.lower().map(interest_map).fillna(0)
    df["_sort"] += df["orders"] / 50

    top = df.sort_values("_sort", ascending=False).iloc[0]
    return {"top_product": str(top.get("idea_name", "N/A")), "top_phrase": str(top.get("phrase", ""))}


def build_report(content_data, trend_data, product_data):
    """Build the full markdown report."""
    today = date.today().isoformat()
    lines = []

    lines.append(f"# {BRAND_NAME} Weekly Report")
    lines.append(f"**Date:** {today}")
    lines.append(f"**Generated by:** Dar Drip OS")
    lines.append("")
    lines.append("---")
    lines.append("")

    # CONTENT SECTION
    lines.append("## Content Performance")
    lines.append("")

    if content_data:
        lines.append(f"**Total orders this week:** {content_data.get('total_orders', 0)}")
        lines.append("")

        lines.append("### Best Hook")
        lines.append(f"> {content_data.get('best_hook', 'No data yet')}")
        lines.append(f"- Views: {content_data.get('best_hook_views', 0):,}")
        lines.append(f"- Format: {content_data.get('best_hook_format', 'N/A')}")
        lines.append("")

        lines.append("### Best Format")
        lines.append(f"- **{content_data.get('best_format', 'N/A')}** (avg {content_data.get('best_format_avg_views', 0):,} views)")
        lines.append("")

        lines.append("### Top Trend Source")
        lines.append(f"- {content_data.get('top_trend_source', 'Organic')}")
        lines.append("")

        # Winners
        winners = content_data.get("winners", [])
        lines.append("### Content to Repeat (Winners)")
        if winners:
            for w in winners:
                lines.append(f"- **{w.get('hook', 'N/A')}** | Format: {w.get('format', '')} | Views: {int(w.get('views_24h', 0)):,} | Orders: {int(w.get('orders', 0))}")
        else:
            lines.append("- No clear winners yet. Keep logging.")
        lines.append("")

        # Weak content
        weak = content_data.get("weak", [])
        lines.append("### Content to Kill (Weak)")
        if weak:
            for w in weak:
                lines.append(f"- **{w.get('hook', 'N/A')}** | Format: {w.get('format', '')} | Reason: {w.get('notes', 'N/A')}")
        else:
            lines.append("- Nothing to kill this week.")
        lines.append("")
    else:
        lines.append("No content data found. Log your posts in data/raw/content.csv.")
        lines.append("")

    lines.append("---")
    lines.append("")

    # TRENDS SECTION
    lines.append("## Trend Radar")
    lines.append("")
    top_trends = trend_data.get("top_trends", [])
    if top_trends:
        lines.append("### Top 3 Trends to Use Next")
        for i, t in enumerate(top_trends, 1):
            lines.append(f"{i}. **{t.get('trend_name', 'N/A')}** ({t.get('category', '')}) - Dar Drip Fit: {t.get('dar_drip_fit_score', 0)}/10")
    else:
        lines.append("No trends logged yet. Add to data/raw/trends.csv.")
    lines.append("")

    lines.append("---")
    lines.append("")

    # PRODUCT SECTION
    lines.append("## Product of the Week")
    lines.append("")
    if product_data:
        lines.append(f"**{product_data.get('top_product', 'N/A')}** - \"{product_data.get('top_phrase', '')}\"")
        lines.append("")
        lines.append("This product has the strongest combination of interest and performance.")
        lines.append("Consider creating content around it this week.")
    else:
        lines.append("No product ideas logged yet.")
    lines.append("")

    lines.append("---")
    lines.append("")

    # ACTION CHECKLIST
    lines.append("## Action Checklist for This Week")
    lines.append("")
    lines.append("Use this every Sunday to plan the week ahead:")
    lines.append("")
    lines.append("- [ ] Log all content results from last week")
    lines.append("- [ ] Check the trend leaderboard in the dashboard")
    lines.append("- [ ] Repeat the winning hook format")
    lines.append("- [ ] Plan 3 posts using the top trend")
    lines.append("- [ ] Push the top product in at least 2 posts")
    lines.append("- [ ] Check competitor log for new inspiration")
    lines.append("- [ ] Update weekly plan in data/raw/weekly_plan.csv")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(f"*Dar Drip OS | Report generated on {today}*")

    return "\n".join(lines)


def save_report(content):
    """Save the report to /reports folder."""
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    filename = f"week_{date.today().isoformat()}.md"
    filepath = REPORTS_DIR / filename
    filepath.write_text(content, encoding="utf-8")
    print(f"Report saved to {filepath}")
    return filepath


def run():
    """Main entry point."""
    print("Generating Weekly Report...")
    data = load_data()
    content_data = analyze_content(data["content"])
    trend_data = analyze_trends(data["trends"])
    product_data = analyze_products(data["products"])
    report = build_report(content_data, trend_data, product_data)
    filepath = save_report(report)
    print(f"\nReport preview:")
    print(report[:500] + "...")
    print(f"\nFull report at: {filepath}")


if __name__ == "__main__":
    run()
